version: '3.9'
services:
  grader:
    #image: ghcr.io/phakphum-dev/otog-grader:latest
    # image: otog-grader:latest
    privileged: true
    build: .
    container_name: otog-grader
    volumes:
      - ./source:/usr/src/app/source:rw
    networks:
      - otog-network
    env_file:
      - .env
    command: python3 -u src/mainHttpSync.py

networks:
  otog-network:
    name: otog-network
