# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: Deploy Grader
    uses: appleboy/ssh-action@0.1.2
    with: 
      host: ${{secrets.SSH_HOST}}
      key: ${{secrets.SSH_KEY}}
      username: ${{secrets.SSH_USERNAME}}
      
      script: |
        cd otog/otog-grader
        git pull origin main
        echo 'Deployment successful to digital ocean'
